## This is completed you do not need to alter
###############################################
---
apiVersion: v1
kind: Secret
metadata:
  name: database
data:
  user-password: 'c3VwZXJzM2NyM3Q='
  root-password: 'c3VwZXJzM2NyM3RSb290'
