---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
    tier: mysql
spec:
  ports:
    - port: 3306
  ##
  # Create service selector labels here
  ##
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-mysql
data:
  ##
  # create non-sensative data attributes
  ##
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
    tier: mysql
spec:
  ##
  # Create app label selectors here
  ##
  template:
    ##
    # Create metadata labels here
    ##
    spec:
      containers:
      - image: mysql:8.0
        name: mysql
        env:
        ##
        # mount non-sensitive environment vars from configmap
        # MYSQL_DATABASE | MYSQL_USER
        ##

        ##
        # mount sensitive environment vars from secret
        # MYSQL_ROOT_PASSWORD | MYSQL_PASSWORD
        ##
        ports:
        - containerPort: 3306
          name: mysql
      ##
      # define volume mounts here, be sure to reference
      # the PVC in your container spec
      ##
---
##
# Create persistent volume claim here
##
